DROP TABLE IF EXISTS krolestwo CASCADE;

DROP TABLE IF EXISTS zamek CASCADE;

DROP TABLE kopalnia_zlota;

DROP TABLE tartak;

DROP TABLE IF EXISTS potwory CASCADE;

DROP TABLE krolestwo_potwory;

DROP TABLE IF EXISTS zamek CASCADE;

DROP TABLE IF EXISTS rycerz CASCADE;

DROP TABLE umiejetnosc_specjalna;
